### ISSUE TITLE
Provide testing scripts for OPTIMSoC

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-ci#21]
@imphil is going to provide testing scripts, which we can use for demo purposes.

**Comment by oleg-nenashev** [comment]
@imphil gentle ping

**Comment by imphil** [comment]
@oleg-nenashev still in the works, I had some trouble with the testing framework. But looks good now, ETA today

**Comment by imphil** [comment]
This took much longer than expected, but at least the non-FPGA part is now working and integrated into optimsoc master.

I guess the best documentation how to run the builds and tests is the travis configuration, available at https://github.com/optimsoc/sources/blob/master/.travis.yml

It is possible to generate the test output in the JUnit XML format by running
`pytest -s -v test/systemtest/test_tutorial.py --junitxml=test_results.xml`

I guess the next step is getting the pipeline in Jenkins running equivalent to what we do in Travis. In the meantime I'll add the FPGA tests, something we cannot test in Travis right now.

**Comment by imphil** [comment]
I've just added the testing infrastructure for FPGA-based tests to optimsoc master.

Testing the hardware requires a `localconfig.yaml` file to be present in either a location specified by `$OPTIMSOC_TEST_LOCALCONF` or in `~/.config/optimsoc/test-localconf.yaml`. I don't know what's easier to realize in Jenkins, I guess adding the file to the `lcci` home directory should do the trick. An example file is part of the repository in `test/localconf.yaml.example`

I'll connect the board to the slave node tomorrow morning; with that everything should be ready to run the tests there.

**Comment by oleg-nenashev** [comment]
@imphil Thanks a lot for you effort.
I'll try to get something running today and/or tomorrow

**Comment by imphil** [comment]
I just found out that we'll have a scheduled power outage in the whole building on Saturday, so the node we planned on using won't be available. I'll think about another way and let you know.

Also note that I'll be leaving to Bologna tomorrow morning, so if anything needs to be physically changed here we should do that today.

**Comment by imphil** [comment]
@oleg-nenashev the hostname of the test node changed to `stu45.clients.eikon.tum.de`, everything else stays the same. The nexys4 ddr board is connected to this host as well.

I've manually tested the build + test of optimsoc on that node and created a `~/.config/optimsoc/test-localconf.yaml` file with the correct settings to talk to the FPGA board, so that should all work out of the box.

**Comment by oleg-nenashev** [comment]
Done. It's something I can use.
Current state: https://ci.librecores.org/job/Sandbox/job/oleg-nenashev/job/OPTIMSoC/3/console (need to fix environment)

Also created #26 as a follow-up
