### ISSUE TITLE
Update FuseSoC demos to the recent versions of FuseSOC and tools

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-ci#49]
All demos were created in 2017, and they are quite outdated now. It would be great to update Docker images and the LibreCores Pipeline Library so that we run demos with recent versions of the tools.

* https://github.com/librecores/librecores-pipeline-lib
* https://github.com/librecores/docker-images
* https://github.com/olofk/fusesoc/releases/tag/1.9 . Other tools also may need an update

**Comment by olofk** [comment]
That would be great. Happy to assist
